maze_file: "example_mazes/maze.m"

ai_enabled: true
# planner can be one of the following: online / astar  / sat
planner: online
#TODO: If planner is not online and deterministic_monsters = false we should throw a runtime exception
deterministic_monsters: true
training_episodes: 50
test_episodes: 50

#How px a cell should be (width and height), our image file has image with size
#22*22 and line thickness is 1 so this must be 22 + 1 + 1 = 24
block_size: 24
dot_color: 192,192,0
maze_color: 5,100,5
cell_color: 0,0,0