maze_file: "/Users/berk/Desktop/myNewCodes/Published/pacman_planner/example_mazes/maze.m"
block_size: 24
ai_enabled: true
online_planning: true
deterministic_monsters: false
training_episodes: 50
test_episodes: 50